### ISSUE TITLE
Error on django-admin.py syncdb

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/graphite-web#1252]
With current master version 67e463e1efa85b8c5cf022f9abffa3d739175d1e when executed django-admin.py syncdb  I got this error

````
.root:graphite-web > django-admin.py syncdb --settings=graphite.settings
Traceback (most recent call last):
  File "/usr/bin/django-admin.py", line 2, in <module>
    from django.core import management
  File "/usr/lib/python2.6/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/usr/lib/python2.6/site-packages/django/utils/version.py", line 7, in <module>
    from django.utils.lru_cache import lru_cache
  File "/usr/lib/python2.6/site-packages/django/utils/lru_cache.py", line 28
    fasttypes = {int, str, frozenset, type(None)},
                    ^
SyntaxError: invalid syntax
```

I have these instal.led versions.

```
.root:graphite-web > pip freeze
argparse==1.3.0
cairocffi==0.7
cffi==1.1.2
Django==1.8.2
django-tagging==0.4
ethtool==0.6
gunicorn==19.3.0
iniparse==0.3.1
isodate==0.5.0
iwlib==1.0
M2Crypto==0.20.2
mocker==1.1.1
pulp-agent==2.4.0
pulp-common==2.4.0
pulp-rpm-common==2.4.0
pulp-rpm-handlers==2.4.0
pycparser==2.14
pycurl==7.19.0
pygpgme==0.1
pyOpenSSL==0.10
PyPAM==0.5.0
pyparsing==1.5.7
python-dateutil==1.4.1
python-dmidecode==3.10.13
python-memcached==1.47
pytz==2015.4
qpid-python==0.22
rhnlib==2.5.22
rhsm==1.9.7
simplejson==2.1.6
Twisted==15.2.1
txAMQP==0.4
urlgrabber==3.9.1
wheel==0.24.0
whisper==0.9.10
whitenoise==1.0.6
yum-metadata-parser==1.1.2
zope.interface==4.1.2
```

I've tested with old Django-1.4 version ( which I have in older installations) and I got this other error.

````
.root:graphite-web > django-admin.py syncdb --settings=graphite.settings
Could not import graphite.local_settings, using defaults!
/opt/graphite/webapp/graphite/settings.py:233: UserWarning: SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security
  warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')
Traceback (most recent call last):
  File "/usr/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.6/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.6/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.6/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.6/site-packages/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/usr/lib/python2.6/site-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/usr/lib/python2.6/site-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/usr/lib/python2.6/site-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/usr/lib/python2.6/site-packages/django/db/models/loading.py", line 67, in _populate
    self.load_app(app_name)
  File "/usr/lib/python2.6/site-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/usr/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/events/models.py", line 4, in <module>
    from tagging.managers import ModelTaggedItemManager
  File "/usr/lib/python2.6/site-packages/tagging/managers.py", line 7, in <module>
    from tagging.models import Tag
  File "/usr/lib/python2.6/site-packages/tagging/models.py", line 6, in <module>
    from django.utils.encoding import smart_text
ImportError: cannot import name smart_text
```

**Comment by brutasse** [comment]
The first error is probably because you're using Python 2.6 with Django 1.8. The last version to support Python 2.6 is Django 1.7.

The second error is due to a django-tagging/Django incompatibility. In this case you probably need to downgrade django-tagging as well.

**Comment by toni-moreno** [comment]
After switch to Django 1.7

**Comment by toni-moreno** [comment]
```
.root:graphite-web > pip freeze
....
Django==1.7
django-tagging==0.3.6
....
graphite-web==0.10.0a0
....
```
we got this new error:

```
root:graphite-web > django-admin.py syncdb --settings=graphite.settings
Traceback (most recent call last):
  File "/usr/bin/django-admin.py", line 2, in <module>
    from django.core import management
  File "/usr/lib/python2.6/site-packages/django/core/management/__init__.py", line 68
    commands = {name: 'django.core' for name in find_commands(__path__[0])}
                                      ^
SyntaxError: invalid syntax
```

**Comment by brutasse** [comment]
Ah yes sorry, 1.7 already doesn't work with Python 2.6. You need Django 1.6 or lower.

See https://docs.djangoproject.com/en/1.8/faq/install/#what-python-version-can-i-use-with-django

**Comment by toni-moreno** [comment]
After switch to 1.6 syncdb worked fine. 

But I've finished all my new config and I got and Apache error when I connect to the http://graphite_url/

This is the apache error.log 
```
[Fri Jun 19 09:25:45 2015] [error] mod_wsgi (pid=20146): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Fri Jun 19 09:25:45 2015] [error] mod_wsgi (pid=20146): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Fri Jun 19 09:25:45 2015] [error] Traceback (most recent call last):
[Fri Jun 19 09:25:45 2015] [error]   File "/opt/graphite/conf/graphite.wsgi", line 4, in <module>
[Fri Jun 19 09:25:45 2015] [error]     from graphite.wsgi import application
[Fri Jun 19 09:25:45 2015] [error]   File "/opt/graphite/webapp/graphite/wsgi.py", line 21, in <module>
[Fri Jun 19 09:25:45 2015] [error]     application = DjangoWhiteNoise(application)
[Fri Jun 19 09:25:45 2015] [error]   File "/usr/lib/python2.6/site-packages/whitenoise/django.py", line 31, in __init__
[Fri Jun 19 09:25:45 2015] [error]     settings_key = 'WHITENOISE_{}'.format(attr.upper())
[Fri Jun 19 09:25:45 2015] [error] ValueError: zero length field name in format
```

**Comment by brutasse** [comment]
Ghaa… Now that's whitenoise that isn't compatible with python 2.6.

Do you have 2.7 available? Otherwise you'll probably have to stick to graphite-web 0.9.x.

**Comment by deniszh** [comment]
Maybe removing whitenoise ("pip uninstall whitenoise") module helps?

**Comment by toni-moreno** [comment]
I 'm on a RHEL6.4 with a closed corportive yum repo. So I'm not able to upgrade python.

There is any way to disable only whitenoise ? what commit was the last before the whitenoise?

**Comment by deniszh** [comment]
Maybe we need to import whitenoise only if python version is 2.7 ?

**Comment by deniszh** [comment]
@toni-moreno , please try replace wsgi.py with this version - https://gist.github.com/deniszh/8863e5412df438150a48

**Comment by toni-moreno** [comment]
@deniszh , are you referring to the /opt/graphite/webapp/graphite/wsgi.py  file?

**Comment by deniszh** [comment]
yes

**Comment by toni-moreno** [comment]
@deniszh It seems to be working fine now !!! Lots of thanks!!

when are you planning to update master branch with this patch ?

**Comment by deniszh** [comment]
Yes, will make PR then.

**Comment by deniszh** [comment]
https://github.com/graphite-project/graphite-web/pull/1254

**Comment by toni-moreno** [comment]
Hi @deniszh @brutasse 

After reviewing again I've noticed that  I can not see metric names and Y labels on the png's .

![image](https://cloud.githubusercontent.com/assets/5883405/8253492/eda1bf50-1690-11e5-9f6d-31e6594627da.png)

Is like no text could be rendered , but any excepcion / error found in files
```
Fri Jun 19 14:53:52 2015 :: Retrieval of carbon.agents.*.cpuUsage took 0.028361
Fri Jun 19 14:53:52 2015 :: Rendered PNG in 0.065290 seconds
Fri Jun 19 14:53:52 2015 :: Total rendering time 0.115250 seconds

```

Any idea ?

these are my python modules.

```
[TST][pmeredbt03].root:graphite > pip freeze
argparse==1.3.0
cairocffi==0.7
cffi==1.1.2
Django==1.6
django-tagging==0.3.6
ethtool==0.6
gunicorn==19.3.0
iniparse==0.3.1
isodate==0.5.0
iwlib==1.0
M2Crypto==0.20.2
mocker==1.1.1
pulp-agent==2.4.0
pulp-common==2.4.0
pulp-rpm-common==2.4.0
pulp-rpm-handlers==2.4.0
pycparser==2.14
pycurl==7.19.0
pygpgme==0.1
pyOpenSSL==0.10
PyPAM==0.5.0
pyparsing==1.5.7
python-dateutil==1.4.1
python-dmidecode==3.10.13
python-memcached==1.47
pytz==2015.4
qpid-python==0.22
rhnlib==2.5.22
rhsm==1.9.7
simplejson==2.1.6
Twisted==15.2.1
txAMQP==0.4
urlgrabber==3.9.1
wheel==0.24.0
whisper==0.9.10
whitenoise==1.0.6
yum-metadata-parser==1.1.2
zope.interface==4.1.2
```

**Comment by toni-moreno** [comment]
forced aliasByNode() doen't work 

![image](https://cloud.githubusercontent.com/assets/5883405/8253898/4aada4ea-1694-11e5-9385-ef5cad79a292.png)


if forced json format

```
http://graphite_host/render/?format=json&target=aliasByNode(carbon.agents.*.creates%2C2)&from=-5min
```

I got the correct target as you can see.

```

[{"target": "host-wr03c", "datapoints": [[0.0, 1434718800], [0.0, 1434718860], [0.0, 1434718920], [0.0, 1434718980], [0.0, 1434719040]]}, {"target": "host-wr03b", "datapoints": [[0.0, 1434718800], [0.0, 1434718860], [0.0, 1434718920], [0.0, 1434718980], [0.0, 1434719040]]}, {"target": "host-wr03a", "datapoints": [[0.0, 1434718800], [0.0, 1434718860], [0.0, 1434718920], [0.0, 1434718980], [0.0, 1434719040]]}, {"target": "host-wr03d", "datapoints": [[0.0, 1434718800], [0.0, 1434718860], [0.0, 1434718920], [0.0, 1434718980], [0.0, 1434719040]]}]
```

**Comment by toni-moreno** [comment]
I can now see text after forcing display font-face and font-style ? Whats the matter?

![image](https://cloud.githubusercontent.com/assets/5883405/8254046/707a0492-1695-11e5-9fb2-a6e2a6ec40fb.png)

**Comment by brutasse** [comment]
What version of Cairo do you have? There are reports of broken graphs on recent versions. Cairo 1.12.6 seems to be working without issues.

**Comment by toni-moreno** [comment]
Hi @brutasse I have installed 

cairo-1.8.8-3.1.el6.x86_64.

```
Name        : cairo
Arch        : x86_64
Version     : 1.8.8
Release     : 3.1.el6
Size        : 779 k
Repo        : installed
From repo   : anaconda-RedHatEnterpriseLinux-201301301459.x86_64
Summary     : A 2D graphics library
URL         : http://cairographics.org
License     : LGPLv2 or MPLv1.1
Description : Cairo is a 2D graphics library designed to provide high-quality display
            : and print output. Currently supported output targets include the X Window
            : System, OpenGL (via glitz), in-memory image buffers, and image files (PDF,
            : PostScript, and SVG).
            :
            : Cairo is designed to produce consistent output on all output media while
            : taking advantage of display hardware acceleration when available (e.g.
            : through the X Render Extension or OpenGL).
```

As a workarround I  have created the graphTemplates.conf and changed on the default section the fontItalic to true: 

```
fontSize = 12
fontBold = False
fontItalic = True
```

![image](https://cloud.githubusercontent.com/assets/5883405/8278076/fe8fc5de-18c8-11e5-9971-954c2829b628.png)


And now we can see text , but I'm afraid on how to fix this error and how can impact on production servers. 

There is any way to check cairo logs? or related debug info?

**Comment by toni-moreno** [comment]
@brutasse I've checked version In another graphite installation that have the same cairo version, and is working ok.

This other platform has :
graphite-web  from master (commit : 8f13d44d446acfaecefb438f1f4b8f56e5164092)

cairo-1.8.8-3.1.el6.x86_64

```
root:/root > pip freeze
argparse==1.2.2
cairocffi==0.6
carbon==0.9.10
carbonate==0.2.2
cffi==0.8.6
Django==1.4
django-tagging==0.3.1
ethtool==0.6
graphite-web==0.10.0a0
gunicorn==19.1.1
iniparse==0.3.1
iotop==0.3.2
isodate==0.5.0
iwlib==1.0
M2Crypto==0.20.2
mocker==1.1.1
pulp-agent==2.4.0
pulp-common==2.4.0
pulp-rpm-common==2.4.0
pulp-rpm-handlers==2.4.0
pycparser==2.10
pycurl==7.19.0
pygpgme==0.1
pyOpenSSL==0.10
PyPAM==0.5.0
pyparsing==1.5.7
python-dateutil==1.4.1
python-dmidecode==3.10.13
python-memcached==1.47
pytz==2014.10
qpid-python==0.22
rhnlib==2.5.22
rhsm==1.12.5
simplejson==2.1.6
Twisted==11.1.0
txAMQP==0.4
urlgrabber==3.9.1
whisper==0.9.10
yum-metadata-parser==1.1.2
zope.interface==4.1.1
```

And working ok

![image](https://cloud.githubusercontent.com/assets/5883405/8278908/9bdc0c70-18cf-11e5-861e-32933f96a5c2.png)

maybe something related to the graphite or cairocffi releases?

**Comment by toni-moreno** [comment]
Hi @brutasse  , I've finally found the fix for this problem. 

As in this link somebody says  (http://serverfault.com/questions/579850/new-graphite-installation-doesnt-render-fonts-in-graphs-except-courier) Centos and Redhat misses needed fonts packages.

after installed them I can now see rendered graphs correctly
```
yum install dejavu-sans-fonts.noarch dejavu-serif-fonts.noarch
```

**Comment by brutasse** [comment]
@toni-moreno great, thanks for investigating and letting us know!

**Comment by evansd** [comment]
Just to let you know that as of v2.0.1 WhiteNoise supports Python 2.6 (and is now tested with that) so you can now remove the version check if you want to.

**Comment by deniszh** [comment]
@evansd - in perfect world - yes, but in reality we need to extend check logic IMO:
if python == 2.6 and whitenoise >= 2.0.1 OR python == 2.7...

**Comment by evansd** [comment]
Ah I see: you're not in control of the version of WhiteNoise installed. That does make things more complicated.

**Comment by deniszh** [comment]
@evansd - yep. But thanks for support of python 2.6 anyway - it will make life happier :+1: :)

**Comment by deniszh** [comment]
@evansd - maybe you can advise me do we have a way how we can check whitenoise version?
If I understand correctly - whitenoise.version will not work, right?

**Comment by evansd** [comment]
I've now added a ` __version__` attribute to WhiteNoise and created a pull request which checks this:
https://github.com/graphite-project/graphite-web/pull/1296
