### ISSUE TITLE
Django sql error: 'Query' object has no attribute 'having'

### ISSUE THREAD

**Issue by meldavis** [graphite-project/graphite-web#1502]
I installed graphite-web on a debian system.  
- graphite-web version 0.9.15
- django version 1.9.5  
which initially failed to migrate various tables. 
I got past that by
```
graphite-manage migrate --run-syncdb
```
it failed with error ```"Query object has no attribute 'having'"``

Per Issue: https://github.com/graphite-project/graphite-web/issues/1425
django 1.9 is not supported, so I deleted the database and downgraded to django 1.8.12

No problem installing the tables with ```graphite-manage syncdb```.  But I get the same ``` "Query object has no attribute 'having'"``
Is this error indicative of another version conflict? Or is this unique to debian and/or my system?

Error log:
```
 File "/usr/share/graphite-web/graphite.wsgi", line 18, in <module>
   import graphite.metrics.search
 File "/usr/lib/python2.7/dist-packages/graphite/metrics/search.py", line 6, in <module>
   from graphite.storage import is_pattern, match_entries
 File "/usr/lib/python2.7/dist-packages/graphite/storage.py", line 9, in <module>
   from graphite.remote_storage import RemoteStore
 File "/usr/lib/python2.7/dist-packages/graphite/remote_storage.py", line 8, in <module>
   from graphite.util import unpickle
 File "/usr/lib/python2.7/dist-packages/graphite/util.py", line 81, in <module>
   defaultUser = User.objects.get(username='default')
 File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method

 File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 381, in get
   self._populate_pk_values(objs)
 File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 240, in __len__
   compiler.annotation_col_map)
 File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 1074, in _fetch_all
   def defer(self, *fields):
 File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 52, in __iter__

 File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
   sql, params = self.as_sql()
 File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 388, in as_sql
   having, h_params = self.compile(self.query.having)
AttributeError: 'Query' object has no attribute 'having'
```

**Comment by meldavis** [comment]
It looks like it is a debian-releated error.   A lot of path and permission errors.

**Comment by deniszh** [comment]
Also please note that 0.9.15 maybe not compatible with Django 1.9 at all

**Comment by deniszh** [comment]
This PR https://github.com/graphite-project/graphite-web/pull/1471 add suport of Django 1.9 to master branch, but not 0.9.x

**Comment by meldavis** [comment]
Just as an FYI: I do have graphite 0.9.15 working with django 1.9.5 on debian.

After installing, install databases: ```graphite-manage migrate --run-syncdb```

Debian specific:
- change ownership of /var/log/graphite to www-data:www-data
- change ownership of /var/lib/graphite to www-data:www-data
Debian did not install graphite/build-index.sh
Copy graphite/build-index.sh from github to /usr/share/graphite-web/bin/

Generally:
The python-tagging for django on pypi, and the one installed by debian, does not support django 1.9.  The latest python-tagging on github, supports only django 1.9.  So, I modified /usr/lib/python2.7/dist-packages/tagging/templatetags/tagging_tags.py to support either either version of django.
